### ISSUE TITLE
Can't manipulate payload the way it described in documentation

### ISSUE THREAD

**Issue by igorlesnenko** [apollographql/graphql-subscriptions#113] opened 2017-10-09 22:03 UTC
```
const SOMETHING_UPDATED = 'something_updated';

export const resolvers = {
  Subscription: {
    somethingChanged: {
      resolve: (payload, args, context, info) => {
        // Manipulate and return the new value

        return payload;
      },
      subscribe: () => pubsub.asyncIterator(SOMETHING_UPDATED),
    },
  },
}
```

Looks like, I have to return `payload.somethingChanged` for it to work, not just `return payload;`

**Comment by tim-soft** [comment] 2017-10-13 16:18
It really depends what your payload contains versus what you are expecting to receive on the client

**Comment by amitport** [comment] 2017-11-14 14:24
@tim-soft can you give an example? when will `somethingChanged` be used and when it won't?

**Comment by ravenscar** [comment] 2017-11-24 21:28
I've found that where:

```
export const resolvers = {
  Subscription: {
    thing: {
      subscribe: () => pubsub.asyncIterator(TOPIC),
    },
  },
}
```

will work

```
export const resolvers = {
  Subscription: {
    thing: {
      resolve: (payload) => payload,
      subscribe: () => pubsub.asyncIterator(TOPIC),
    },
  },
}
```
won't work.

So it's not really clear to me what the resolve does, how it works, or what shape it should return in order to work. The only documentation I could find: https://www.apollographql.com/docs/graphql-subscriptions/subscriptions-to-schema.html#subscription-server is so vague as to be useless, and poking about the repos I haven't been able to find a test case for it.

I'll try to trace it with a debugger on Monday to see what is going wrong but I imagine it would be an order of magnitude easier to just implement a `withMap` analogous to https://github.com/apollographql/graphql-subscriptions/blob/master/src/with-filter.ts and use this for the transforms.

**Comment by tim-soft** [comment] 2017-11-27 02:14
Some action occurs and you call your subscription function. You pass some data along with this call. 

Your subscription resolver function executes, you do something with that data you've passed to it and it publishes/returns a payload to a channel. This is like sending a message to a slack channel. Your UI or whatever is subscribed to this channel and recieves that _payload object_ as the _message_.

Your UI needs to know what to do with that payload. Let's say you have a list of things and each one has a delete button. You click delete and this thing is deleted from the database via a mutation. You want to have _real time_ UI, which means the item should be removed from the front end.

How does this happen? 
1. Delete mutation fires
2. In mutation, after successful delete, call subscription.
3. Subscription emits the ID of the thing that was deleted as a payload.
4. UI is subscribed to the channel that the subscription was emitted to and recieves that payload.
5. On the client side, you find the deleted item in the Apollo cache and remove it. List of things rerenders and looks _real time_.

**Comment by ravenscar** [comment] 2017-11-27 04:47
@tim-soft Thanks for the detailed explanation of the lifecycle of the events.

The problem I was having was happening during returning the data to the client, and I could see an error in one of the frames of the websocket connection for subscriptions.

I had built my subscriptions using the default pubsub implementation, and not using resolvers - as most of the examples/docs show subscriptions being built. I'm going to call this the implicit resolver as opposed to the named resolver when using it explicitly. 

As the app matured I have migrated this to use CQRS with some SNS/SQS queues and a custom pubsub implementation. 

This has the side effect of changing the shape of the payload being emitted from the AsyncIterator so I needed to use a resolve function to alter the shape of the payload (not to do any additional resolving via dataloaders, just altering shape).

The issue is that the payload of the implicit resolver and the named resolver are required to have a different shape, so in my example above here are the two shapes required for success:

implicit resolver / subscribe only:
```
{
  thing : {
    id: ...
  }
}
```

named resolver / subscribe & resolver:
```
{
  id: ...
}
```

This caused me a lot of confusion as the error message, examples, and documentation did not provide me with enough information to know that when I was using a named resolver I must alter the shape of the data away from what worked in the implicit resolver.

This is the exact issue that igorlesnenko outlined above (although it's now solved for me and all working).

**Comment by mfix22** [comment] 2018-01-11 20:41
> export const resolvers = {
  Subscription: {
    thing: {
      resolve: (payload) => payload,
      subscribe: () => pubsub.asyncIterator(TOPIC),
    },
  },
}
won't work.

@ravenscar 

Did you try: 
```javascript
export const resolvers = {
  Subscription: {
    thing: {
      resolve: (payload) => payload.thing, // Note the field 'thing'
      subscribe: () => pubsub.asyncIterator(TOPIC),
    },
  },
}
```

**Comment by gauravmakkar** [comment] 2018-01-12 09:54
Facing same problem.

Receiving the packet in subscription :
{
  "type": "data",
  "id": "1",
  "payload": {
    "errors": [
      {
        "message": "resolveFn is not a function",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "path": [
          "userListUpdated"
        ]
      }
    ]
  }
} 

Subscription: {
    commentAdded: {
      subscribe: withFilter(() => pubsub.asyncIterator(COMMENT_ADDED_TOPIC), (payload, args) => {
        return payload.commentAdded.repository_name === args.repoFullName;
      }),
    },
    userListUpdated: {
      subscribe: pubsub.asyncIterator(USER_LIST_UPDATED),
      resolve: payload => payload,
    },


  },

**Comment by mfix22** [comment] 2018-01-12 17:32
Right and I am wondering if you could try instead of this:
```javascript
userListUpdated: {
  subscribe: pubsub.asyncIterator(USER_LIST_UPDATED),
  resolve: payload => payload,
},
```
```javascript
userListUpdated: {
  subscribe: pubsub.asyncIterator(USER_LIST_UPDATED),
  resolve: payload => payload.userListUpdated,
},
```

**Comment by gauravmakkar** [comment] 2018-01-14 05:35
That worked! Thanks @mfix22

**Comment by mfix22** [comment] 2018-01-14 08:07
Sweet 😄! Please close this issue @igorlesnenko if this is settled.

**Comment by jamiter** [comment] 2018-02-09 10:52
I don't think this should be closed yet, or maybe a discussion elsewhere should start, because the API isn't clear for many people.

Checkout these cases, where `subscribe` is always `pubsub.asyncIterator(FOO)`, and `foo` is a String in the schema. We publish with `pubsub.publish(FOO, payload)`.

 #|  resolver setup | publish payload | result
--|------|---------|-------
1 | `foo: {subscribe}` | `{foo:'bar'} ` | `{foo:'bar'} ` |
2 |`foo: {subscribe, resolve: payload => payload}`| `{foo:'bar'}` | `{foo:'[Object object]'}`*
3| `foo: {subscribe, resolve: ({foo}) => foo}`| `{foo:'bar'}` | `{foo:'bar'}` 
4| `foo: {subscribe, resolve: payload => payload}`| `'bar' ` | `{foo:'bar'}`
5| `foo: {subscribe, resolve: ({foo}) => foo}`| `'bar' ` | `{foo:null}`

> _* #.2 returns `{ foo: { foo: 'bar' } }`, but the schema says it's a String_

Notice how you always need to publish `foo`, except for #.4. I didn't expect that to work. And the `[Object object]` result left me in the dark for a while...

If this is actually the API that is expected, we at least need to update the docs to show that you need to extract the correct value from the payload.

For me it was confusing why the payload can't always simply be `'bar'`, but that might have to do with more complex examples where you only want a part of a payload.

**Comment by grantwwu** [comment] 2018-10-02 17:22
It looks like the MR addressing this issue was merged.

**Closed by grantwwu** 2018-10-02 17:22 UTC
