### ISSUE TITLE
does it support persistgraphql?

### ISSUE THREAD

**Issue by veeramarni** [apollographql/graphql-subscriptions#115] opened 2017-10-15 23:32 UTC
I'm facing below issue which I have opened issue [here](https://github.com/apollographql/persistgraphql/issues/49)

I'm using 
```
    "subscriptions-transport-ws": "^0.8.3"
    "graphql-subscriptions": "^0.5.0",
```

**Comment by Poincare** [comment] 2017-10-27 04:17
I'm unclear what you mean by this. What is the precise issue (with error) that you're currently running into and how could I go about reproducing it?

**Comment by grantwwu** [comment] 2018-09-26 20:19
I'm going to close this issue for now since it's been a while there was last any activity on it, and it was not clear what action to take here.  I'm going to leave conversation open, so feel free to respond if you want to pursue this further.

**Closed by grantwwu** 2018-09-26 20:19 UTC
Labels: waiting-for-response
