### ISSUE TITLE
[Question] how to use with graphql-js?

### ISSUE THREAD

**Issue by eladams** [apollographql/graphql-subscriptions#94] opened 2017-07-26 16:19 UTC
It seems that `SubscriptionManager[@deprecated]` was meant for that so I'm a bit lost 🗺

**Comment by NeoPhi** [comment] 2017-07-26 18:14
Newer versions of `graphql-js` support subscriptions directly. For a step by step walkthrough of using this package I recommend looking through: http://dev.apollodata.com/tools/graphql-subscriptions/index.html

**Comment by sibelius** [comment] 2017-07-26 18:38
is there any example of `graphql-js` with this package?

**Comment by NeoPhi** [comment] 2017-07-26 19:18
In the documentation mentioned above at http://dev.apollodata.com/tools/graphql-subscriptions/setup.html#subscription-server you'll see it uses `import { execute, subscribe } from 'graphql';`

**Comment by sibelius** [comment] 2017-07-26 19:19
I think the problem is with this doc

```jsx
Subscription: {
        commentAdded: {
          subscribe: withFilter(() => pubsub.asyncIterator('commentAdded'), (payload, variables) => {
             return payload.commentAdded.repository_name === variables.repoFullName;
          }),
        }
    },
```

it is not in graphql-js notation, I think this cause some problems for newcomers

**Comment by eladams** [comment] 2017-07-27 10:30
Exactly @sibelius, do you have any suggestions?

**Comment by igorlesnenko** [comment] 2017-09-28 00:36
You just need to put `subscribe` function on the same level where `resolve` is located. Example:

```js
 let subscription = {
      type: new GraphQLObjectType({
        name: subscriptionName,
        fields: () => ({
          mutation: { type: GraphQLString },
          node: {
            type: modelTypes[model.getName()]
          }
        })
      }),
      subscribe: () => {
        return PubSubService.asyncIterator(subscriptionName);
      }
};
```

**Comment by grantwwu** [comment] 2018-09-27 15:46
This issue _seems_ to be resolved, closing, let me know if it's not

**Closed by grantwwu** 2018-09-27 15:46 UTC
